// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvVXzLfYksgH46MW91Nf81EzaVsoOFJE',
    appId: '1:113688836597:android:8b747d114a78a4121388bc',
    messagingSenderId: '113688836597',
    projectId: 'in-service-1d030',
    storageBucket: 'in-service-1d030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMc7Qz6owevxoi4G-iOlAkCk3Ow8WrHuU',
    appId: '1:113688836597:ios:f15d5f3f705f37ac1388bc',
    messagingSenderId: '113688836597',
    projectId: 'in-service-1d030',
    storageBucket: 'in-service-1d030.firebasestorage.app',
    androidClientId: '113688836597-r5br5rcvfs985hgo7392tg8tstvd8bi6.apps.googleusercontent.com',
    iosClientId: '113688836597-954mrcaumtshcl1t7pqu32kkr5fbgpdf.apps.googleusercontent.com',
    iosBundleId: 'com.tarekzeyadproduction.inservice',
  );
}
